# Site settings
title: Roopesh Singh | Webpages
description: My digital space, a collection of my past, present, and future endeavors.
  This site serves as a platform to document and share my work,
  interests, and experiences.
url: "https://roopesh-singh.com" # the base hostname & protocol
permalink: /blog/:title/

# Social
author:
  name: Roopesh Singh # Added author name for consistency and potential use in templates
  facebook: # Removed empty entries, add URLs if available
  twitter: https://twitter.com/roopesh_singh02
  linkedin:
  googleplus:
  pinterest:
  instagram:


# Defaults - More explicit and organized
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes" #  collection
    values:
      layout: "note-item" #  singular form, more consistent


# Collections -  defined at the top level
collections:
  notes:
    output: true
    permalink: /notes/:path/


# Input methods -  grouping
input_types:
  text:
  textarea:
  email:
  date:
  checkbox:
  radio:
  number:
  submit:

# Form Types -  grouping
form_engines:
  cloudcannon:
  formspree:
  formbucket:

# Comments
comments:
  provider: "facebook"
  facebook:
    appid: #  Add your Facebook App ID
    num_posts: 5 #  (default) - Explicitly stated
    colorscheme: "light" # (default), "dark" - Explicitly stated

# Exclude - Keeping regular posts and linked posts seperately
exclude:
  - linked_posts